# Generated by Django 2.0.13 on 2019-03-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSN', models.IntegerField(default=0)),
                ('harness_length', models.IntegerField(default=0)),
                ('gross_weight', models.IntegerField(default=0)),
                ('atmospheric_pressure', models.IntegerField(default=0)),
                ('room_temperature', models.IntegerField(default=0)),
            ],
        ),
    ]
