# Generated by Django 2.0.13 on 2019-03-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='atmospheric_pressure',
            new_name='Atmospheric_pressure',
        ),
        migrations.RenameField(
            model_name='aircraft',
            old_name='gross_weight',
            new_name='Fuel_Capacity_on_Left_Wing',
        ),
        migrations.RenameField(
            model_name='aircraft',
            old_name='harness_length',
            new_name='Fuel_Capacity_on_Right_Wing',
        ),
        migrations.RenameField(
            model_name='aircraft',
            old_name='room_temperature',
            new_name='Fuel_Quantity_on_Left_Wing',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='Airport',
            field=models.TextField(default='Heaven'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='Flight_No',
            field=models.TextField(default='CR7'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='Fuel_Quantity_on_Right_Wing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='Gross_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='Harness_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='Maximum_Altitude_to_be_Reached',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='Room_temperature',
            field=models.IntegerField(default=0),
        ),
    ]
