# Generated by Django 2.0.13 on 2019-03-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS_app', '0003_auto_20190307_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsfeed',
            old_name='Airport',
            new_name='HeadLine',
        ),
    ]
