$(document).ready(function() {
    console.log( "ready!" );
    
    var msg1='<div class="container-fluid" id="a320"> <button type="button" class="btn btn-primary btn-lg btn-block">A320 Program</button> <br><br><form> <div class="form-group"> <label foar="MSN">MSN</label> <input type="number" class="form-control" id="MSN" aria-describedby="msnHelp" placeholder="Enter MSN Number" required> </div><div class="form-group"> <label for="Harness">Harness Length</label> <input type="number" class="form-control" id="Harness" aria-describedby="HarnessHelp" placeholder="Enter Harness Length" required> </div><div class="form-group"> <label for="Gross">Gross Weight</label> <input type="number" class="form-control" id="Gross" aria-describedby="GrossHelp" placeholder="Enter Gross Weight" required> </div><div class="form-group"> <label for="Atmospheric">Atmospheric Pressure</label> <input type="number" class="form-control" id="Atmospheric" aria-describedby="AtmosphericHelp" placeholder="Enter Atmospheric Pressure" required> </div><div class="form-group"> <label for="Airport">Airport</label> <input type="text" class="form-control" id="Airport" aria-describedby="AirportHelp" placeholder="Enter Airport" required> </div><div class="form-group"> <label for="fclw">Fuel Capacity On Left Wing</label> <input type="number" class="form-control" id="fclw" aria-describedby="fclwHelp" placeholder="Enter Fuel Capacity On Left Wing" required> </div><div class="form-group"> <label for="fcrw">Fuel Capacity On Right Wing</label> <input type="number" class="form-control" id="fcrw" aria-describedby="fcrwHelp" placeholder="Enter Fuel Capacity On Right Wing" required> </div><div class="form-group"> <label for="fqlw">Fuel Quantity On Left Wing</label> <input type="number" class="form-control" id="fqlw" aria-describedby="fqlwHelp" placeholder="Enter Fuel Quantity On Left Wing" required> </div><div class="form-group"> <label for="fqrw">Fuel Quantity On Right Wing</label> <input type="number" class="form-control" id="fqrw" aria-describedby="fqrwHelp" placeholder="Enter Fuel Quantity On Right Wing" required> </div><div class="form-group"> <label for="maxalt">Maximum Altitude to be Reached</label> <input type="number" class="form-control" id="maxalt" aria-describedby="maxaltHelp" placeholder="Enter Maximum Altitude to be Reached" required> </div><div class="form-group"> <label for="Fn">Flight Number</label> <input type="text" class="form-control" id="Fn" aria-describedby="FnHelp" placeholder="Enter Flight Number" required> </div><button type="submit" class="btn btn-primary">Submit</button> </form> </div>';
    var msg2='<div class="container-fluid" id="a330"> <button type="button" class="btn btn-primary btn-lg btn-block">A330 Program</button> <br><br><form> <div class="form-group"> <label foar="MSN">MSN</label> <input type="number" class="form-control" id="MSN" aria-describedby="msnHelp" placeholder="Enter MSN Number" required> </div><div class="form-group"> <label for="Harness">Harness Length</label> <input type="number" class="form-control" id="Harness" aria-describedby="HarnessHelp" placeholder="Enter Harness Length" required> </div><div class="form-group"> <label for="Gross">Gross Weight</label> <input type="number" class="form-control" id="Gross" aria-describedby="GrossHelp" placeholder="Enter Gross Weight" required> </div><div class="form-group"> <label for="Atmospheric">Atmospheric Pressure</label> <input type="number" class="form-control" id="Atmospheric" aria-describedby="AtmosphericHelp" placeholder="Enter Atmospheric Pressure" required> </div><div class="form-group"> <label for="Airport">Airport</label> <input type="text" class="form-control" id="Airport" aria-describedby="AirportHelp" placeholder="Enter Airport" required> </div><div class="form-group"> <label for="fclw">Fuel Capacity On Left Wing</label> <input type="number" class="form-control" id="fclw" aria-describedby="fclwHelp" placeholder="Enter Fuel Capacity On Left Wing" required> </div><div class="form-group"> <label for="fcrw">Fuel Capacity On Right Wing</label> <input type="number" class="form-control" id="fcrw" aria-describedby="fcrwHelp" placeholder="Enter Fuel Capacity On Right Wing" required> </div><div class="form-group"> <label for="fqlw">Fuel Quantity On Left Wing</label> <input type="number" class="form-control" id="fqlw" aria-describedby="fqlwHelp" placeholder="Enter Fuel Quantity On Left Wing" required> </div><div class="form-group"> <label for="fqrw">Fuel Quantity On Right Wing</label> <input type="number" class="form-control" id="fqrw" aria-describedby="fqrwHelp" placeholder="Enter Fuel Quantity On Right Wing" required> </div><div class="form-group"> <label for="maxalt">Maximum Altitude to be Reached</label> <input type="number" class="form-control" id="maxalt" aria-describedby="maxaltHelp" placeholder="Enter Maximum Altitude to be Reached" required> </div><div class="form-group"> <label for="Fn">Flight Number</label> <input type="text" class="form-control" id="Fn" aria-describedby="FnHelp" placeholder="Enter Flight Number" required> </div><button type="submit" class="btn btn-primary">Submit</button> </form> </div>';
    var msg3='<div class="container-fluid" id="a350"> <button type="button" class="btn btn-primary btn-lg btn-block">A350 Program</button> <br><br><form> <div class="form-group"> <label foar="MSN">MSN</label> <input type="number" class="form-control" id="MSN" aria-describedby="msnHelp" placeholder="Enter MSN Number" required> </div><div class="form-group"> <label for="Harness">Harness Length</label> <input type="number" class="form-control" id="Harness" aria-describedby="HarnessHelp" placeholder="Enter Harness Length" required> </div><div class="form-group"> <label for="Gross">Gross Weight</label> <input type="number" class="form-control" id="Gross" aria-describedby="GrossHelp" placeholder="Enter Gross Weight" required> </div><div class="form-group"> <label for="Atmospheric">Atmospheric Pressure</label> <input type="number" class="form-control" id="Atmospheric" aria-describedby="AtmosphericHelp" placeholder="Enter Atmospheric Pressure" required> </div><div class="form-group"> <label for="Airport">Airport</label> <input type="text" class="form-control" id="Airport" aria-describedby="AirportHelp" placeholder="Enter Airport" required> </div><div class="form-group"> <label for="fclw">Fuel Capacity On Left Wing</label> <input type="number" class="form-control" id="fclw" aria-describedby="fclwHelp" placeholder="Enter Fuel Capacity On Left Wing" required> </div><div class="form-group"> <label for="fcrw">Fuel Capacity On Right Wing</label> <input type="number" class="form-control" id="fcrw" aria-describedby="fcrwHelp" placeholder="Enter Fuel Capacity On Right Wing" required> </div><div class="form-group"> <label for="fqlw">Fuel Quantity On Left Wing</label> <input type="number" class="form-control" id="fqlw" aria-describedby="fqlwHelp" placeholder="Enter Fuel Quantity On Left Wing" required> </div><div class="form-group"> <label for="fqrw">Fuel Quantity On Right Wing</label> <input type="number" class="form-control" id="fqrw" aria-describedby="fqrwHelp" placeholder="Enter Fuel Quantity On Right Wing" required> </div><div class="form-group"> <label for="maxalt">Maximum Altitude to be Reached</label> <input type="number" class="form-control" id="maxalt" aria-describedby="maxaltHelp" placeholder="Enter Maximum Altitude to be Reached" required> </div><div class="form-group"> <label for="Fn">Flight Number</label> <input type="text" class="form-control" id="Fn" aria-describedby="FnHelp" placeholder="Enter Flight Number" required> </div><button type="submit" class="btn btn-primary">Submit</button> </form> </div>';
    var msg4='<div class="row bg-primary" style="height: 70px;"> <p class="text-center text-light" style="margin: auto;font-size: -webkit-xxx-large;">AIR-BUZZ </p></div><br><div class="row" style="height:100px"> <div class="col-4 align-self-start"> <img src="1.jpg" class="img-fluid" alt="Sampleimage1" height="100px" width="100px"> </div><div class="col-4 align-self-center"> <span class="text-warning">Sample News Text</span> </div><div class="col-3 align-self-end bg-warning" style="width: 70%"> News Headline </div></div><br><div class="bg-primary" style="height: 20px;"></div><br><div class="row" style="height:100px"> <div class="col-4 align-self-end"> <img src="2.jpg" class="img-fluid" alt="Sampleimage1" height="100px" width="100px"> </div><div class="col-4 align-self-start"> <span class="text-warning">Sample News Text</span> </div><div class="col-3 align-self-center bg-warning" style="width: 70%"> News Headline </div></div><br><div class="bg-primary" style="height: 20px;"></div>';
    
    $(document).on("click","#A320b",function(){
    	$("#content").html(msg1);
    });

    $(document).on("click","#A330b",function(){
    	$("#content").html(msg2);
    });

    $(document).on("click","#A350b",function(){
    	$("#content").html(msg3);
    });

    $(document).on("click","#Home",function(){
    	$("#content").html(msg4);
    });




});
